# yaml 语法 https://blog.csdn.net/IT_faquir/article/details/79842885
spring:
 application:
  name: dubbo-spring-boot-starter
 dubbo:
  server: true
  registry:
   registry: zookeeper://127.0.0.1:2181
  protocol:
   name: dubbo